- name: Add MariaDB repository
  yum_repository:
    name: mariadb
    description: mariadb YUM repo
    file: MariaDB
    baseurl: http://yum.mariadb.org/{{mariadb_version}}/centos{{ansible_distribution_major_version}}-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
  when: ansible_distribution == 'CentOS'

- name: Add MariaDB repository
  yum_repository:
    name: mariadb
    description: mariadb YUM repo
    file: MariaDB
    baseurl: http://yum.mariadb.org/{{mariadb_version}}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
  when: ansible_distribution == 'Amazon'

- block:
  - name: Install MariaDB
    yum: 
      name: [MariaDB-server,MariaDB-client]

  - name: Create Databases Directory
    file:
      path: /data/mysql
      state: directory
      owner: mysql
      group: mysql
    
  - name: Copy MariaDB Configuration
    template: src=my.cnf.jinja2 dest=/etc/my.cnf

  - name: init Source data
    shell: rm -rf /data/mysql/*;mysql_install_db --user=mysql --datadir=/data/mysql

  - name: Restart MariaDB
    service:
      name: mariadb
      state: restarted
      enabled: yes

  - name: Create a MariaDB  symbolic link
    file:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      state: link
    with_items:
      - {src: '/etc/my.cnf',dest: /data/config/my.cnf}

  when: mariadb_install_server == "package"

- name: Install MariaDB Client
  yum: 
    name: MariaDB-client
  when: not mariadb_install_server 