- name: Create Remote User
  mysql_user: 
    login_user: root 
    login_password: "{{mariadb_root_password}}"
    login_unix_socket: /data/mysql/mysqld.sock
    name: root
    host: '%'
    password: "{{mariadb_root_password}}"
    priv: '*.*:ALL,GRANT'

- name: Drop localhost User
  mysql_user:
    login_user: root 
    login_password: "{{mariadb_root_password}}"
    login_unix_socket: /data/mysql/mysqld.sock
    name: root
    host: '{{item}}'
    state: absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes